@startuml
left to right direction

object "adotante: Adotante" as Adotante
object "sistema: Sistema PetCar" as Sistema
object "banco: Banco de Dados" as BD
object "apiMapas: API de Mapas/Localização" as ApiMapas

Adotante -- Sistema
Sistema -- BD
Sistema -- ApiMapas

note left of Adotante
1. acessarListaAnimais()
2. aplicarFiltros(especie, porte, idade, localizacao)
end note

note right of Sistema
1.3 exibirListaAnimais()
2.7 exibirAnimaisFiltradosComDistanciaEMapa()
end note

note top of BD
1.1 buscarAnimaisDisponiveis()
1.2 retornarListaAnimaisDisponiveis()
2.1 buscarAnimaisPorFiltros()
2.2 retornarAnimaisFiltrados()
end note

note right of ApiMapas
2.3 calcularProximidade()
2.4 retornarDistanciasAproximadas()
2.5 gerarMapa(localizacaoAnimal)
2.6 retornarMapaLocalizacao()
end note

@enduml